title: Dylan Campana Photography
description: New York-based photographer and visual artist
baseurl: "" # the subpath of your site
url: "" # the base hostname & protocol for your site

# Image directories
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# Site settings
header:
  title: Dylan
  subtitle: Campana

footer:
  name: Dylan Campana
  bio: New York-based photographer and visual artist working primarily with portraiture and urban landscapes.

social_urls:
  instagram: "https://instagram.com/dylandeluge/"

author: Dylan Campana
web_design: Custom Design

# Build settings
markdown: kramdown
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# Collections
collections:
  galleries:
    output: true

# Include static files
include:
  - _pages
  - images

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# Processing
safe: false
encoding: utf-8
highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Sass settings
sass:
  style: compressed
  sass_dir: _sass

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "images"
    values:
      image: true