title: Dylan Campana Photography
description: New York-based photographer and visual artist
baseurl: "" # the subpath of your site
url: "" # the base hostname & protocol for your site

# Image directories
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# Site settings
header:
  title: Dylan
  subtitle: Campana

footer:
  name: Dylan Campana
  bio: New York-based photographer and visual artist working primarily with portraiture and urban landscapes.

social_urls:
  instagram: "https://instagram.com/dylandeluge/"

author: Dylan Campana
web_design: Custom Design

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Collections
collections:
  galleries:
    output: true

# Include static files
include:
  - _pages

# Processing
safe: false