# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Dylan"
subtitle: "Dylan Again"
author: "Dylan"
header:
 title: "Photography"
 subtitle: "by Dylan Victor René '5Skin' Campana"
footer:
 name: "Hey there, my name is Dylan"
 bio: "I am a Dylan."
 github: "Want a website like this for DYlan.?"
web_design: "BC"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
# exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/dylandeluge"
  github: "https://www.github.com/dylancampana"
